fordgobike<-read.csv(file = "C:/Users/Tiange/Desktop/fordgobike.csv", header = T,sep=',')
library(png)
library(grid)
library(ggplot2)
library(sqldf)
library(dplyr)
library(ggmap)
head(fordgobike)
str(fordgobike)
